### ISSUE TITLE
Tight timing for two notebooks

### ISSUE THREAD

**Issue by ascheliga** [dlab-berkeley/Python-Data-Wrangling#4]
Going through two notebooks in three hours felt too tight. Many participants have (good) questions for Pandas basics

**Comment by tomvannuenen** [comment]
Thanks for flagging this @ascheliga. Do you have any suggestions to make either of the two notebooks shorter?

**Comment by ascheliga** [comment]
In the workshop right now (led by @ Renata). Will follow-up in an hour!

**Comment by ascheliga** [comment]
Had plenty of time with both notebooks! Comment closed. We just got a bit spooked midway through the workshop. Spent 2 hours on the first notebook and 1 hour on the second.
