### ISSUE TITLE
Error in .dropna() in 02_python_data_wrangling

### ISSUE THREAD

**Issue by ascheliga** [dlab-berkeley/Python-Data-Wrangling#7]
For some versions of Pandas, you need to use subset in brackets `unemployment.dropna(subset=['unemployment_rate'])`. Fix the example to include brackets. And maybe add a caveat about the version update.

For me, I needed brackets when using Pandas v1.3.5

Tagging @rbarreto

**Comment by tomvannuenen** [comment]
added
